### ISSUE TITLE
Is there a simple way to add a background color...

### ISSUE THREAD

**Issue by stacksmith** [cbaggers/cepl.fond#1]
This is great.  Is there an easy way to make it blend with the background?  Or at least set another background color?
subpixel antialiasing would be ideal of course...

![temp](https://user-images.githubusercontent.com/732800/65072212-48de2680-d945-11e9-87d2-d99266988268.png)

**Comment by azimut** [comment]
I use:
```
(defparameter *font-blending*
  (make-blending-params :source-alpha :one-minus-src-alpha))
```
and wrap map-g with ```(with-blending *font-blending*)```

Also found that stepping the alpha make is look better at borders
